config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

root to: 'homes#index'

  resources :postcodedata

  resources :postcodedata do
    collection { post :import}
  end

  resources :faildata

  resources :faildata do
    collection { post :import}
  end


  resources :postcodes
=======
>>>>>>> fd31c8cfa51fdee45960d86fa085cefc2ebef888
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/postcode.rb
class Postcode < ApplicationRecord

validates :postcode, :presence => true, length: { minimum: 5 }, :postcode_format => true

end

app/controllers/postcodes_controller.rb
class PostcodesController < ApplicationController
  before_action :set_postcode, only: [:show, :edit, :update, :destroy]

  # GET /postcodes
  # GET /postcodes.json
  def index
    @postcodes = Postcode.all
  end

  # GET /postcodes/1
  # GET /postcodes/1.json
  def show
  end

  # GET /postcodes/new
  def new
    @postcode = Postcode.new
  end

  # GET /postcodes/1/edit
  def edit
  end

  # POST /postcodes
  # POST /postcodes.json
  def create
    @postcode = Postcode.new(postcode_params)

    respond_to do |format|
      if @postcode.save
        format.html { redirect_to @postcode, notice: 'This is a valid UK postcode!' }
        format.json { render :show, status: :created, location: @postcode }
      else
        format.html { render :new }
        format.json { render json: @postcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postcodes/1
  # PATCH/PUT /postcodes/1.json
  def update
    respond_to do |format|
      if @postcode.update(postcode_params)
        format.html { redirect_to @postcode, notice: 'Postcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @postcode }
      else
        format.html { render :edit }
        format.json { render json: @postcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postcodes/1
  # DELETE /postcodes/1.json
  def destroy
    @postcode.destroy
    respond_to do |format|
      format.html { redirect_to postcodes_url, notice: 'Postcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postcode
      @postcode = Postcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postcode_params
      params.require(:postcode).permit(:postcode)
    end
end

app/helpers/postcodes_helper.rb
module PostcodesHelper
end

app/views/postcodes/_form.html.erb
<%= form_for(postcode) do |f| %>
  <% if postcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postcode.errors.count, "Error") %></h2>

      <ul>
      <% postcode.errors.full_messages.each do |message| %>
        <li><h3><%= message %></h3></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>

<div class="container">

  <div class="field">
    <h3><%= f.label :postcode %>
    <%= f.text_field :postcode %></h3>
  </div>


<br>
  <div class="actions">
  <%= f.submit 'Validate', :class=>"btn btn-warning"%>
  <%= link_to 'Home', root_path, :class=>"btn btn-default" %>
  </div>

</div>
<% end %>

app/views/postcodes/_validation_errors.html.erb
<% if @postcode.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited from being saved</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/postcodes/edit.html.erb
<h1>Editing Postcode</h1>

<%= render 'form', postcode: @postcode %>

<%= link_to 'Show', @postcode %> |
<%= link_to 'Back', postcodes_path %>

app/views/postcodes/index.html.erb
<div class="container">

<h4><p id="notice"><%= notice %></p></h4>

<h1>Valid Postcodes</h1>

<table>
  <thead>
    <tr>
      <th><h3>Postcode</h3></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postcodes.each do |postcode| %>
      <tr>
        <td><h3><%= postcode.postcode %></h3></td>
        <td><h3><%= link_to 'Show', postcode, :class=>"btn btn-info" %><h3></td>
        <td><h3><%= link_to 'Destroy', postcode, :class=>"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %><h3></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Validate', new_postcode_path, :class=>"btn btn-warning" %>

</div>

app/views/postcodes/new.html.erb
<div class="container">

<h1>Validate a single postcode</h1>

<%= render 'form', postcode: @postcode %>


</div>

app/views/postcodes/show.html.erb
<div class="container">


<h2><p id="notice"><%= notice %></p></h2>

<h4><p><strong>Postcode:</strong> <%= @postcode.postcode %></p></h4>

<%= link_to 'Home', root_path, :class=>"btn btn-default" %>
<%= link_to 'New One', new_postcode_path, :class=>"btn btn-warning" %>


</div>